### ISSUE TITLE
Frontend using `reportPostViews()` but not passing any postIds

### ISSUE THREAD

**Issue by mfogel** [real-social-media/frontend#18]
It appears the frontend is doing a fair number of calls to `Mutation.reportPostViews` but passing in an empty list for the `postIds` parameter. Ex: `Mutation.reportPostViews(postIds: [])`. The backend then responds to the frontend with an error message `Client Error: A minimum of 1 post id must be reported`

It looks like in the last week this has happened 172 times on the beta backend and 82 times on production backend.

Not really a big deal from a backend perspective, but it is filling up one of the error logs.

**Comment by azimgd** [comment]
Indeed, after investigation i see that it happens when i scroll through main feed. I will add a filter there. Thanks.

**Comment by azimgd** [comment]
Implemented within https://github.com/real-social-media/frontend/commit/5933d44b69cffb73d254e38139f691ceda933dcb
