### ISSUE TITLE
Sign up / sign in issues  2/17/2019

### ISSUE THREAD

**Issue by real-ian** [real-social-media/frontend#22]
- [x] The current production version of our app asks me which google email I would like to use to login. Now (in the latest testflight build 1.2.3.178), I see this screen the first time I login with google, but all other times I sign in, it just takes me immediately to the last google account I used, without prompting me to select which one. This leaves me to believe that "signout" is no longer clearing/caching my google data. Is it possible to have users see this "select google account" screen every login like it used to? This will allow them to select which google account to use & switch between accounts, while clearing potentially corrupt google data on signout.
- [ ]  "Send Confirmation Email" button on signup should automatically be hit. This screen on signup shouldn't exist. Users should be taken directly to "Enter the code we sent to" screen 
- [x] After tapping confirmation link emailed to me, tapping "login", then entering a username & full name, the app crashed. I sent my crash report. Once I opened the app again I was already signed in & everything was working properly, but because of this, I was never prompted to create a profile picture. 
- [x] all errors on the "enter your full name & reserve your new username" screen should be red. For example "no whitespace" & "full name must be at least 2 characters"
- [x] The latest version of the app always crashes for me after entering me full name and username during signup. I think something is wrong with the create profile picture screen.
- [ ] After confirming email, users are given a popup that "they have confirmed successfully confirmed account, you can signin now". Their email & password is already entered. This step should not exist, we should automatically login the user after email confirmation.
- [x] People don't think they can add a photo from library on the upload profile photo screen. Please add a button which says "Choose a photo from 
- [x] When putting a space character at the end of a username during signup, the error shown is "the username is already reserved". This also happens when placing an emoji in the username field. We should catch & display the actual error coming from the backend.

**Comment by azimgd** [comment]
- "Send Confirmation Email" button on signup should automatically be hit. This screen on signup shouldn't exist. Users should be taken directly to "Enter the code we sent to" screen

I think we still need have this step as when i mistype my email/username it won't immediately try to create new user based on wrong entry. 

-  After confirming email, users are given a popup that "they have confirmed successfully confirmed account, you can signin now". Their email & password is already entered. This step should not exist, we should automatically login the user after email confirmation.

This is not an easy fix for now as aws-amplify doesn't have a way to authorize users right after their account is verified. I will meanwhile think how can we do this programmatically tho

@real-ian

**Comment by real-ian** [comment]
@azimgd 

1. For "Send Confirmation Email", currently I still see "change email" as a button / option on the page where it asks you to enter the code. I don't think it does/should create a user until that user is confirmed. A user object should only be created after the email is confirmed. From what I have seen, another user can still sign up using a different password on that same email, until some user confirms it, so either uniqueness is not enforced on the email key, or the user object is not created until after email confirmation. Since a user can still change their email (even after sending the code), by pressing the "change email address" button, I still feel we should remove this step. I've seen a few people waiting for the email, thinking it already sent, without knowing to press the "Send Confirmation Email" button. What do you think?

2. After confirming email, users are given a popup that "they have confirmed successfully confirmed account, you can signin now". Their email & password is already entered. This step should not exist, we should automatically login the user after email confirmation.

It appears you already store the email/password on the front-end since it autofills. Some quick questions:
2.a Is that frontend password stored in a way where it's encoded on the user device? If so, what key/cert is it encoded using?
2.b Since we already have the key in plaintext autofilled into the fields, why can't we just simulate the press of the login button (1 time)? We have everything we need locally for email/password based sign up. For users who signed up using email & password, we could autopress login, for google users, we could autopress "login with google". What do you think?
2.c Please hide the users autofilled plaintext password from the password field. It should be Asterisk characters when autofilled, unless replaced for the user. For example, Password would become something like ********. Pressing summit should decode & submit the correct password for the form to the alpine cognito login.
