### ISSUE TITLE
Album support

### ISSUE THREAD

**Issue by real-ian** [real-social-media/frontend#9]
Albums are a new GraphQL model which has the following properties:
```
type Album {
    id: ID!
    created_at: AWSDateTime #time when the album was created
    updated_at: AWSDateTime #updated whenever a post is added to the album
    name: String
    description: Text #caption/description
    album_art_url: String # This is automatically generated & updated by the backend anytime an album or it's posts are modified. 
    Posts: [Posts] # ordered list of post uuid's inside this album
} 
```

Posts also have a new property to help determine if they are in an album
```
album_id: [Albums]
```

- [ ] Add "Album" option / dropdown option to the **create & edit post page**. Users should be able to select an existing album from this dropdown or create a new album by typing the name of the album. This is where a user creates albums & adds a post to an album. A user should be able to modify/edit an existing post, add it to an album, or change the album it is in.

- [ ] Albums should appear in the news feed just like posts. The news feed should be sorted based on "created_at". If a post and an album are created at the same exact time, it does not matter which is on top of the other in the news feed (similar to what would happen if two posts were created at the exact same time). An album's "thumbnail", should be it's the album_art_url property. This is an image/video generated by the backend which contains a collage of all  posts inside an album. This album_art is generated & updated by the backend anytime an Album's posts are modified. It becomes a video if the album contains any videos. When tapped, the album should open a menu which contains a grid (similar to the user profile screen) of the users posts inside that album. This menu's title/caption should be the album title.

- [ ] Albums should appear in the news feed alongside posts. Their picture should be the album_art_url property which comes from the backend. The news feed should be sorted by the "created_at" property containing individual posts, and albums (which may also contain an already displayed post). 

Duplicate posts may appear in the news feed as individual posts, and that same post inside the album_art of an album which contains that post. This will look especially strange for albums with only a single post, as a user may see the same post's image in the news feed twice (once as the post itself, and another as the album art of the album which contains that post), this is ok.

- [ ] Add tabs to the user profile page (for the current user or any user profile). When viewing a profile, you should see the tabs:
"All" (this is the default), "Photos", "Videos", "Albums". All should be selected by default & it should show albums, photos, and videos, all in order of when they were created (created_at). 

- [ ] Posts which are in the news feed & belong to an Album (posts which have an album_uuid property set), should have an icon in the top right corner of the post image showing that it's inside an album. Something like: https://www.onlinewebfonts.com/icon/299591 This will inform followers who see that post that it's inside of an album. 

Tapping this post should show in the "similar posts" when scrolling down, other posts in that same album.

- [ ] Posts which are in the news feed & belong to an Album (posts which have an album_uuid property set), should be on a carousel, swiping left/right on that post in the news feed should go to the next/previous post in the album.

**Comment by mfogel** [comment]
Looks good. @azim I put a plan for new graphql mutations, queries and types to support this functionality here https://github.com/real-social-media/backend/issues/9#issuecomment-578785056 which I will update as I work on it. And please let me know if you can think of something speced in this ticket that those graphql additions might not support

The feed with albums & posts - I think it might be best to have the backend put both Albums & Posts in the feed and then the frontend just queries "give me the user's feed" and displays it. Thoughts?  I did not include this in the graphql schema changes referenced above.

A question for you @real-ian : if a user adds a post to an existing album, should the album re-appear in the user's feed? Maybe get bumped to the top? Or should an album only appear in the user's feed when it's created?

BTW: I am so glad we are doing this project with graphql, rather than a REST api. Strongly-typed API's for the win.

**Comment by real-ian** [comment]
@mfogel 

- _The feed with albums & posts - I think it might be best to have the backend put both Albums & Posts in the feed and then the frontend just queries "give me the user's feed" and displays it. Thoughts? I did not include this in the graphql schema changes referenced above._ 

I like this idea, I just worry that the front-end may be looking for specific properties/attributes which may not exist on albums. 

- _A question for you @real-ian : if a user adds a post to an existing album, should the album re-appear in the user's feed? Maybe get bumped to the top? Or should an album only appear in the user's feed when it's created?_

Posts will be in the news feed twice, once inside the "album_art" of the album post, and another as the standalone post. When a new post is added to an album, that new post will be at the top, no need to bump the entire album again. 

- _Do we want to make the Album name required - ie should a user be able to create an album without a name?_
It should be required, yes. 

Thank you! :)

**Comment by mfogel** [comment]
Thanks @real-ian - sounds good

Re: feed with albums & posts

Graphql has some nice support for this kind of thing (a query where the response is a list of objects of different types). The simplest way for us I think would be with a [union type](https://graphql.org/learn/schema/#union-types), which for us in the schema would probably look like this:

```gql
union FeedItem = Post | Album
```

Then depending on what javascript packages we're using on the frontend, rendering the feed items would either go something like this:

```js
function renderFeedItem(item) {
  if (item isinstanceof Post) { ... render a post ... }
  else if (item isinstanceof Album) { ... render an album ... }
  else { ... log an error... }
}
```

or it might go like this:

```js
function renderFeedItem(item) {
  if (item.__typename == 'Post') { ... render a post ... }
  else if (item.__typename ==  'Album') { ... render an album ... }
  else { ... log an error... }
}
```

More info on using graphql union types (and interfaces) to solve this kind of problem here: https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d

**Comment by azimgd** [comment]
implemented
